### ISSUE TITLE
Bug: "Show only current class" checkbox nonfunctional until recheck

### ISSUE THREAD

**Issue by JamesMDenton** [petikk/pHelperPlugin#13]
**Steps to reproduce:**
1. Create definitions for skills for a class.
2. Log into a different class.

**Expected Result:**
That the "show only current class" checkbox would prevent class abilities from non-current class showing when it is checked by default.

**Actual Result:**
Skills for non-current class still show until you uncheck "show only current class" and then recheck it

**Comment by petikk** [comment]
Already fixed!
Will be included in the next beta release. Thanks for reporting!
