### ISSUE TITLE
Feature Request: "Pause/Resume pHelper" hotkey

### ISSUE THREAD

**Issue by JamesMDenton** [petikk/pHelperPlugin#14]
**Use Cases:**
Quickly pausing skills/definitions that are unwieldy due to current plugin limitations (e.g. Necromancer Devour)
Aiding in pull setup
Aiding in loot pickup
Taking actions that require a small amount of time without plugin automation

**Comment by petikk** [comment]
Already fixed!
Will be included in the next beta release. Thanks for reporting!
