### ISSUE TITLE
Feature Request: Expand/Rework MinimumResourcePercent

### ISSUE THREAD

**Issue by JamesMDenton** [petikk/pHelperPlugin#15]
**Definition Type:** ResourceAmount
**ResourceType:** Primary/Secondary
**Percentage:** Check/Uncheck
**Operator:** Equal to, Less/Greater Than

**Use Cases:** 
Demon Hunter skills that use 2 different resources
Definitions that require more precision than percent
Decreased need to rewrite definitions when resource maximum changes
UI/UX consistency

**Comment by petikk** [comment]
Techincally the MinimumResourcePercent definition checks the resource used by the skill in question.
I thought percentage was sufficient, but I don't think adding it is too much work.

**Comment by JamesMDenton** [comment]
Unfortunately with DH, the big one is Preparation. Doesn't use any resource, and restores either hatred or discipline depending on rune.

**Comment by petikk** [comment]
Done
