### ISSUE TITLE
Feature Request: "CorpsesInRange" Definition

### ISSUE THREAD

**Issue by JamesMDenton** [petikk/pHelperPlugin#17]
**Group:** World
**Definition Type:** CorpsesInRange
**Inverted:** Check/Uncheck
**Range:** 
**Count:**

**Use Case:**
Many necromancer skills depend on corpses in range.
E.g. Devour, needs to be cast when there is a corpse in range to receive any benefit. Without CorpseInRange, any other definition results in casting constantly, or not enough.

**Comment by petikk** [comment]
Thats a good point.
I will think about wether it's worth to try and generify a definition type for that, I suppose that could be used for things like pets as well.

**Comment by petikk** [comment]
Done
