### ISSUE TITLE
ignore pain on character type

### ISSUE THREAD

**Issue by thatoneguy555** [petikk/pHelperPlugin#3]
have skill active checked on skill editor tab, have ignore pain as only skill on that side, have a definition group on skills editor tab, definition group active checked on skills editor tab, on edit definition group i selected add defintion, group i chose "party", on definition type i chose "isskillbuffactiveonheroclass", hero class is necromancer, drop down for buffname as "ignore pain", and hit save. this saved it without inverted checked and it didn't work. i opened it back up and buffname dropdown was empty, so i checked the override selected and put in sno as "79528" and resaved again didn't work, i then used the checkbox for inverted as some in the discord said that was it for them and it still not working. I have relaunched hud after each change and made sure they stuck after the launch, also have tried different character types ie wizard. have tried in town, in a reg rift and in gr none have worked so far

**Comment by petikk** [comment]
I guess thats just how buffs work.
Unfortunately i don't know how TurboHUDs `BuffIsActive` works, but i assume it checks only the first `IconIndex`.

IP might have a different `IconIndex` or Sno on teammates. 
This is a feature which is not yet implemented, after the next update you will be able to set the `IconIndex` yourself.

**Comment by petikk** [comment]
Has been added in the latest beta release!
